### PR TITLE
Upload PL translation and modified index.html file

### PR DESCRIPTION
**Pull request by AviciiPL**

### CODE REVIEW

**Comment by a0ivanov** [comment]
Formally I discarded this pull request but the job has been integrated. Reason: bad line endings in index.html(d5a8bbeb19347cb2ee1f3eabdcee08b33299141d) which causes undesired mess in file history. I put that one-line change at 67c663a2ed88e6abdb223ecf359eb87c37d5a0a6. Also I enabled installer translation in *.iss file(817035786e285d4d7de1b5af1bacc798993df8e7).

**Comment by AviciiPL** [comment]
I don't know why... I've just added ONE line in index.html
.iss file is not translated by me... it's official polish translate on their website for version 5.3.3+...
"I put that one-line change at 67c663a. " thank you... and I told you, I don't like github... :)
Greetings, Avi

**Comment by a0ivanov** [comment]
There are about 30 custom lines at the end of installer's Polish file. If you don't want to translate them, I will disable polish lang in installer, because pure English is more solid than partly translated stuff.

**Comment by AviciiPL** [comment]
I can translate them... and I think I must create a new file and completely translate this from english to polish... so for now: I think it's necessary to disable Polish in installer, but not in htdocs... If I find any translation mistake, I think I can create a new pull request to update my translation (htdocs and installer translation)

**Comment by a0ivanov** [comment]
Disabled Polish in installer at c805217904f1519740ae6cfc4ba595ee3bbc5d93. 

> I think I must create a new file and completely translate this...

I would suggest to translate only custom messages starting from BrowserScriptsDirSelectionMsg1.


Just in case, after all my changes, please reset your "master" branch to commit b7c2c5b595f344f026ba6c5062bcfc60c2226d79 and pull again.
Command for this: `git reset --hard b7c2c5b`
This is required to skip index.html commit issue and avoid merge conflicts.

**Pull request closed without merging**
